version: '3.3'
services:
  web:
       build:
               context: ./php/online-shopping-system
               dockerfile: Dockerfile
       container_name: php_app
       volumes:
          - ./php/online-shopping-system:/var/www/html/
       depends_on: 
         - db  
       ports:
         - 8008:80
